[2024-11-21T11:40:38.692+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T11:40:38.720+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T11:35:14.427550+00:00 [queued]>
[2024-11-21T11:40:38.734+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T11:35:14.427550+00:00 [queued]>
[2024-11-21T11:40:38.735+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T11:40:38.756+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_data_to_postgres> on 2024-11-21 11:35:14.427550+00:00
[2024-11-21T11:40:38.769+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3994) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T11:40:38.772+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'insert_data_to_postgres', 'manual__2024-11-21T11:35:14.427550+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9wf3u0_2']
[2024-11-21T11:40:38.773+0000] {standard_task_runner.py:72} INFO - Started process 3996 to run task
[2024-11-21T11:40:38.774+0000] {standard_task_runner.py:105} INFO - Job 244: Subtask insert_data_to_postgres
[2024-11-21T11:40:38.849+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T11:35:14.427550+00:00 [running]> on host 7a40aa914b11
[2024-11-21T11:40:39.487+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T11:35:14.427550+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T11:35:14.427550+00:00'
[2024-11-21T11:40:39.491+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T11:40:39.493+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T11:40:39.495+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_postgres state:running start_date:2024-11-21 11:40:38.721147+00:00
[2024-11-21T11:40:39.497+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T11:40:39.498+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T11:40:39.554+0000] {base.py:84} INFO - Retrieving connection 'skincare_connection'
[2024-11-21T11:40:39.565+0000] {load.py:101} ERROR - Error inserting data: 'NoneType' object has no attribute 'to_dict'
[2024-11-21T11:40:39.567+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-21T11:40:39.587+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T11:40:39.591+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=insert_data_to_postgres, run_id=manual__2024-11-21T11:35:14.427550+00:00, execution_date=20241121T113514, start_date=20241121T114038, end_date=20241121T114039
[2024-11-21T11:40:39.617+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-21T11:40:39.618+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-21T11:40:39.619+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-11-21 11:35:14.595004+00:00
[2024-11-21T11:40:39.620+0000] {logging_mixin.py:190} INFO - Task hostname:7a40aa914b11 operator:PythonOperator
[2024-11-21T11:40:39.680+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T11:40:39.714+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T11:40:39.721+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
