[2024-11-21T12:25:39.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T12:25:39.504+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.transform_cleaning manual__2024-11-21T12:25:18.278769+00:00 [queued]>
[2024-11-21T12:25:39.514+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.transform_cleaning manual__2024-11-21T12:25:18.278769+00:00 [queued]>
[2024-11-21T12:25:39.515+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T12:25:39.529+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): transform_cleaning> on 2024-11-21 12:25:18.278769+00:00
[2024-11-21T12:25:39.538+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4649) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T12:25:39.540+0000] {standard_task_runner.py:72} INFO - Started process 4651 to run task
[2024-11-21T12:25:39.540+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'transform_cleaning', 'manual__2024-11-21T12:25:18.278769+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpunm7sf_9']
[2024-11-21T12:25:39.541+0000] {standard_task_runner.py:105} INFO - Job 262: Subtask transform_cleaning
[2024-11-21T12:25:39.582+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.transform_cleaning manual__2024-11-21T12:25:18.278769+00:00 [running]> on host 7a40aa914b11
[2024-11-21T12:25:39.908+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='transform_cleaning' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T12:25:18.278769+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T12:25:18.278769+00:00'
[2024-11-21T12:25:39.909+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T12:25:39.910+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T12:25:39.910+0000] {logging_mixin.py:190} INFO - Current task name:transform_cleaning state:running start_date:2024-11-21 12:25:39.505115+00:00
[2024-11-21T12:25:39.911+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T12:25:39.912+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T12:25:39.913+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: clean_data() missing 1 required positional argument: 'df'
[2024-11-21T12:25:39.926+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-21T12:25:39.927+0000] {logging_mixin.py:190} INFO - Task start:2024-11-21 12:25:39.505115+00:00 end:2024-11-21 12:25:39.926588+00:00 duration:0.421473
[2024-11-21T12:25:39.928+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): transform_cleaning> dag:<DAG: etl_pipeline> dagrun:<DagRun etl_pipeline @ 2024-11-21 12:25:18.278769+00:00: manual__2024-11-21T12:25:18.278769+00:00, state:running, queued_at: 2024-11-21 12:25:18.811989+00:00. externally triggered: True>
[2024-11-21T12:25:39.928+0000] {logging_mixin.py:190} INFO - Failure caused by clean_data() missing 1 required positional argument: 'df'
[2024-11-21T12:25:39.929+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=transform_cleaning, run_id=manual__2024-11-21T12:25:18.278769+00:00, execution_date=20241121T122518, start_date=20241121T122539, end_date=20241121T122539
[2024-11-21T12:25:39.940+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T12:25:39.941+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 262 for task transform_cleaning (clean_data() missing 1 required positional argument: 'df'; 4651)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: clean_data() missing 1 required positional argument: 'df'
[2024-11-21T12:25:39.997+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T12:25:40.017+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T12:25:40.023+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
