[2024-11-21T12:35:05.753+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T12:35:05.771+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:34:46.128508+00:00 [queued]>
[2024-11-21T12:35:05.782+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:34:46.128508+00:00 [queued]>
[2024-11-21T12:35:05.783+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T12:35:05.798+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): insert_data_to_postgres> on 2024-11-21 12:34:46.128508+00:00
[2024-11-21T12:35:05.807+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4856) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-21T12:35:05.811+0000] {standard_task_runner.py:72} INFO - Started process 4858 to run task
[2024-11-21T12:35:05.811+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'insert_data_to_postgres', 'manual__2024-11-21T12:34:46.128508+00:00', '--job-id', '284', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5qlj3esw']
[2024-11-21T12:35:05.812+0000] {standard_task_runner.py:105} INFO - Job 284: Subtask insert_data_to_postgres
[2024-11-21T12:35:05.865+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.insert_data_to_postgres manual__2024-11-21T12:34:46.128508+00:00 [running]> on host 7a40aa914b11
[2024-11-21T12:35:06.220+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T12:34:46.128508+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T12:34:46.128508+00:00'
[2024-11-21T12:35:06.222+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-21T12:35:06.223+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-21T12:35:06.224+0000] {logging_mixin.py:190} INFO - Current task name:insert_data_to_postgres state:running start_date:2024-11-21 12:35:05.772942+00:00
[2024-11-21T12:35:06.225+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline and current dag run status:running
[2024-11-21T12:35:06.226+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T12:35:06.272+0000] {base.py:84} INFO - Retrieving connection 'skincare_connection'
[2024-11-21T12:35:06.286+0000] {load.py:83} ERROR - Error inserting data: 'tren'
[2024-11-21T12:35:06.287+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-21T12:35:06.305+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T12:35:06.306+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=insert_data_to_postgres, run_id=manual__2024-11-21T12:34:46.128508+00:00, execution_date=20241121T123446, start_date=20241121T123505, end_date=20241121T123506
[2024-11-21T12:35:06.323+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-21T12:35:06.324+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-21T12:35:06.325+0000] {logging_mixin.py:190} INFO - Dag name:etl_pipeline queued_at:2024-11-21 12:34:46.331149+00:00
[2024-11-21T12:35:06.326+0000] {logging_mixin.py:190} INFO - Task hostname:7a40aa914b11 operator:PythonOperator
[2024-11-21T12:35:06.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T12:35:06.374+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T12:35:06.378+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
